// AUTHENTICATION ACTION TYPES
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

// ABOUT ACTION TYPES
export const SHOW_ROUTER_INFO = "SHOW_ROUTER_INFO";
export const SHOW_REDUX_INFO = "SHOW_REDUX_INFO";
export const SHOW_THUNK_INFO = "SHOW_THUNK_INFO";
export const SHOW_SCSS_INFO = "SHOW_SCSS_INFO";
export const SHOW_NAVIGATION_INFO = "SHOW_NAVIGATION_INFO";
export const SHOW_AUTH_INFO = "SHOW_AUTH_INFO";
export const SHOW_LAYOUT_INFO = "SHOW_LAYOUT_INFO";